In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(
    columns=["Name", "Age", "Height"],
    )
df

Empty DataFrame
Columns: [Name, Age, Height]
Index: []

In [6]:
df.loc[0] = ["Allen", 22, 180]
df
df.loc[1] = ["Jack", 30, 172]
df

    Name  Age  Height
0  Allen   22     180
1   Jack   30     172

In [9]:
df["Age"][1] = 28

/var/folders/rn/dnts2tcx26x1x17_ssv5w7500000gn/T/ipykernel_11377/2063534485.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df["Age"][1] = 28

In [11]:
df

    Name  Age  Height
0  Allen   22     180
1   Jack   29     172

In [12]:
df["Weight"] = [75, 80]
df

    Name  Age  Height  Weight
0  Allen   22     180      75
1   Jack   29     172      80

In [14]:
df.drop("Weight",axis=1)

    Name  Age  Height
0  Allen   22     180
1   Jack   29     172

In [15]:
df

    Name  Age  Height  Weight
0  Allen   22     180      75
1   Jack   29     172      80

In [16]:
df = df.drop("Weight",axis=1)
df

    Name  Age  Height
0  Allen   22     180
1   Jack   29     172

In [17]:
df.drop(1)
df

    Name  Age  Height
0  Allen   22     180
1   Jack   29     172

In [18]:
df = df.drop(1)
df

    Name  Age  Height
0  Allen   22     180

In [19]:
df["Age"] + 10
df

    Name  Age  Height
0  Allen   22     180

In [20]:
df["Age"] + 10

0    32
Name: Age, dtype: int64

In [21]:
df = df["Age"] + 10
df

0    32
Name: Age, dtype: int64

In [22]:
df

0    32
Name: Age, dtype: int64

In [23]:
df = pd.DataFrame(
    columns=["Name", "Age", "Height"],
    )
df

Empty DataFrame
Columns: [Name, Age, Height]
Index: []

In [24]:
df.loc[0] = ["Allen", 22, 180]

In [25]:
df

    Name  Age  Height
0  Allen   22     180

In [26]:
df["Age"] = df["Age"] + 10

In [27]:
df

    Name  Age  Height
0  Allen   32     180

In [28]:
df2 = df.copy()
df2.loc[0, "Age"] = 12

In [29]:
df
df2

    Name  Age  Height
0  Allen   12     180

In [30]:
df

    Name  Age  Height
0  Allen   32     180